require("config.lazy")

require("config.langservers.lua")
require("config.langservers.csharp")
require("config.langservers.java")
require("config.langservers.docker")
require("config.langservers.docker-compose")
require("config.langservers.terraform")
require("config.langservers.marksman")
require("config.langservers.rust")
require("config.langservers.python")
require("config.langservers.typescript")
require("config.langservers.cue")

require("config.cmp")
require("config.treesitter")
